<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup"/>
        <PackageReference Include="AWSSDK.S3"/>
        <ProjectReference Include="../HousingApp.Application/HousingApp.Application.csproj"/>
        <ProjectReference Include="../HousingApp.Domain/HousingApp.Domain.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="bin\"/>
        <Folder Include="obj\"/>
        <Folder Include="Seeder\" />
    </ItemGroup>

</Project>
