<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <UserSecretsId>8c835046-ab94-4e32-8d99-d97b0ec009fe</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Npgsql.OpenTelemetry" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
        <PackageReference Include="Scalar.AspNetCore"/>
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Formatting.Compact" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../HousingApp.Application/HousingApp.Application.csproj"/>
        <ProjectReference Include="..\HousingApp.Infrastructure\HousingApp.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Requests\"/>
    </ItemGroup>

</Project>
