<Project Sdk="Microsoft.NET.Sdk.Web">

<!--  <PropertyGroup>-->
<!--    <TargetFramework>net10.0</TargetFramework>-->
<!--    <Nullable>enable</Nullable>-->
<!--    <ImplicitUsings>enable</ImplicitUsings>-->
<!--  </PropertyGroup>-->

  <PropertyGroup>
      <UserSecretsId>8c835046-ab94-4e32-8d99-d97b0ec009fe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../HousingApp.Application/HousingApp.Application.csproj" />
    <ProjectReference Include="..\HousingApp.Infrastructure\HousingApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
    <Folder Include="Requests\" />
  </ItemGroup>

</Project>
