CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    id text NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);

CREATE TABLE "AspNetUsers" (
    id text NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);

CREATE TABLE booking_statuses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    updated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    is_deleted boolean NOT NULL,
    CONSTRAINT pk_booking_statuses PRIMARY KEY (id)
);

CREATE TABLE rooms_statuses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    updated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    is_deleted boolean NOT NULL,
    CONSTRAINT pk_rooms_statuses PRIMARY KEY (id)
);

CREATE TABLE "AspNetRoleClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    user_id text NOT NULL,
    role_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    user_id text NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE persons (
    user_id character varying(450) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(300) NOT NULL,
    phone_number character varying(50) NOT NULL,
    nationality character varying(50) NOT NULL,
    age integer NOT NULL,
    gender character varying(30) NOT NULL,
    image_url character varying(500),
    birth_date date NOT NULL,
    is_deleted boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT pk_persons PRIMARY KEY (user_id),
    CONSTRAINT fk_persons_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE rooms (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    description character varying(300) NOT NULL,
    price numeric(10,2) NOT NULL,
    person_id character varying(450) NOT NULL,
    room_status_id integer NOT NULL,
    updated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    is_deleted boolean NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (id),
    CONSTRAINT fk_rooms_persons_person_id FOREIGN KEY (person_id) REFERENCES persons (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_rooms_rooms_statuses_room_status_id FOREIGN KEY (room_status_id) REFERENCES rooms_statuses (id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    booker_id character varying(450) NOT NULL,
    room_id integer NOT NULL,
    booking_status_id integer NOT NULL,
    updated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    is_deleted boolean NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_bookings_booking_statuses_booking_status_id FOREIGN KEY (booking_status_id) REFERENCES booking_statuses (id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_persons_booker_id FOREIGN KEY (booker_id) REFERENCES persons (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_rooms_room_id FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE
);

CREATE TABLE room_images (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    image_url text NOT NULL,
    room_id integer NOT NULL,
    updated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    is_deleted boolean NOT NULL,
    CONSTRAINT pk_room_images PRIMARY KEY (id),
    CONSTRAINT fk_room_images_rooms_room_id FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE
);

CREATE INDEX ix_asp_net_role_claims_role_id ON "AspNetRoleClaims" (role_id);

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" (normalized_name);

CREATE INDEX ix_asp_net_user_claims_user_id ON "AspNetUserClaims" (user_id);

CREATE INDEX ix_asp_net_user_logins_user_id ON "AspNetUserLogins" (user_id);

CREATE INDEX ix_asp_net_user_roles_role_id ON "AspNetUserRoles" (role_id);

CREATE INDEX "EmailIndex" ON "AspNetUsers" (normalized_email);

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" (normalized_user_name);

CREATE INDEX ix_bookings_booker_id ON bookings (booker_id);

CREATE INDEX ix_bookings_booking_status_id ON bookings (booking_status_id);

CREATE INDEX ix_bookings_room_id ON bookings (room_id);

CREATE INDEX ix_room_images_room_id ON room_images (room_id);

CREATE INDEX ix_rooms_person_id ON rooms (person_id);

CREATE INDEX ix_rooms_room_status_id ON rooms (room_status_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260314020106_Init', '10.0.3');

COMMIT;

