name: Deploy Application with Docker

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
    workflow_dispatch:
      

jobs:
    build:
        name: Build Docker image and push to repositories
        runs-on: ubuntu-24.04
        environment: itersapiens-prod

        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

            - name: Login to Docker Hub
              uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121

              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push frontend
              uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
              with:
                context: ./frontend
                push: true
                tags: itersapiens/frontend:1.0
                build-args: |
                    VITE_API_URL=https://api.itersapiens.rafael-vargas.dev:${{ vars.BACKEND_PORT}}
                    VITE_GOOGLE_MAPS_API_KEY=${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
                    VITE_GOOGLE_MAPS_ID=${{ secrets.VITE_GOOGLE_MAPS_ID }}
                    VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}

            - name: Build and push backend
              uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
              with:
                context: ./backend
                push: true
                tags: itersapiens/backend:1.0
