name: .NET backend deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'release/**']

permissions:
  contents: read

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    uses: ./.github/workflows/backend-ci-reusable.yml
    with:
      run-unit-tests: true
      run-integration-tests: true
      run-publish: true