# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET unit testing

on:
  push:
    branches: [ 'feature/**' ]
  pull_request:
    branches: [ 'develop' ]

permissions:
  contents: read

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    uses: ./.github/workflows/backend-ci-reusable.yml
    with:
      run-unit-tests: true
      run-integration-tests: false
      run-publish: false

